version: '3.8'

services:
  # CallBot main application with HOST NETWORK for SIP
  callbot:
    build: .
    container_name: callbot-app
    network_mode: "host"  # CRITICAL: Use host network for SIP to work properly
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - DATABASE_URL=sqlite:///callbot.db
      # Your PBX settings
      - SIP_DOMAIN=${SIP_DOMAIN}
      - SIP_USERNAME=${SIP_USERNAME}
      - SIP_PASSWORD=${SIP_PASSWORD}
      - SIP_PORT=${SIP_PORT:-5060}
      # CRITICAL: Tell the bot it's in host network mode
      - DOCKER_HOST_NETWORK=true
      - DOCKER_NETWORK_MODE=host
      # Ollama configuration
      - OLLAMA_URL=${OLLAMA_URL:-http://localhost:11434}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama2}
      - TTS_ENGINE=${TTS_ENGINE:-espeak}  # Use espeak for reliability
      - WHISPER_MODEL_SIZE=${WHISPER_MODEL_SIZE:-base}
      - WHISPER_DEVICE=${WHISPER_DEVICE:-cpu}
    volumes:
      - ./audio_output:/app/audio_output
      - ./logs:/app/logs
      - callbot_data:/app/data
    restart: unless-stopped
    # No ports mapping needed with host network

  # Ollama AI service (also use host network)
  ollama:
    image: ollama/ollama:latest
    container_name: callbot-ollama
    network_mode: "host"  # Use host network
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    profiles:
      - local-ollama

  # Redis (also use host network)
  redis:
    image: redis:7-alpine
    container_name: callbot-redis
    network_mode: "host"  # Use host network
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --port 6379 --bind 127.0.0.1

volumes:
  callbot_data:
    driver: local
  ollama_data:
    driver: local
  redis_data:
    driver: local